# Use a base JDK image
FROM eclipse-temurin:17-jdk-alpine

# Set working directory inside container
WORKDIR /app

# Copy everything into the container
COPY . .

# Build the application
RUN ./gradlew build -x test

# Expose port (same as your Spring Boot server.port)
EXPOSE 8080

# Run the JAR file
CMD ["java", "-jar", "build/libs/portfolio-0.0.1-SNAPSHOT.jar"]
